global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: ytm-player
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials_file: /tmp/metrics-token
    static_configs:
      - targets:
          - app:3001
